content-type:
  org:
    input-files: ["tests/data/main_readme.org", "tests/data/interface_emacs_readme.org"]
    input-filter: null
    compressed-jsonl: "tests/data/.notes.json.gz"
    embeddings-file: "tests/data/.note_embeddings.pt"

  ledger:
    input-files: null
    input-filter: tests/data/*.beancount
    compressed-jsonl: tests/data/.transactions.jsonl.gz
    embeddings-file: tests/data/.transaction_embeddings.pt

  image:
    input-directory: "tests/data"
    embeddings-file: "tests/data/.image_embeddings.pt"
    batch-size: 50
    use-xmp-metadata: "no"

  music:
    input-files: ["tests/data/music.org"]
    input-filter: null
    compressed-jsonl: "tests/data/.songs.jsonl.gz"
    embeddings-file: "tests/data/.song_embeddings.pt"

search-type:
  asymmetric:
    encoder: "sentence-transformers/msmarco-MiniLM-L-6-v3"
    cross-encoder: "cross-encoder/ms-marco-MiniLM-L-6-v2"

  image:
    encoder: "clip-ViT-B-32"

processor:
  conversation:
    openai-api-key: null
    conversation-logfile: "tests/data/.conversation_logs.json"