name: khoj
channels:
  - conda-forge
dependencies:
  - aiofiles=0.8.0=pyhd8ed1ab_0
  - asgiref=3.4.1=pyhd8ed1ab_0
  - attrs=21.2.0=pyhd8ed1ab_0
  - brotlipy=0.7.0=py39h5161555_1001
  - ca-certificates=2022.6.15=h4653dfc_0
  - certifi=2022.6.15=py39h2804cbe_0
  - cffi=1.14.6=py39hda8b47f_0
  - chardet=4.0.0=py39h2804cbe_1
  - charset-normalizer=2.0.0=pyhd8ed1ab_0
  - click=8.0.1=py39h2804cbe_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - cryptography=3.4.7=py39h73257c9_0
  - dataclasses=0.8=pyhc8e2a94_3
  - dateparser=1.1.1=pyhd8ed1ab_0
  - et_xmlfile=1.0.1=py_1001
  - fastapi=0.68.2=pyhd8ed1ab_0
  - filelock=3.0.12=pyh9f0ad1d_0
  - freetype=2.10.4=h17b34a0_1
  - future=0.18.2=py39h2804cbe_3
  - h11=0.12.0=pyhd8ed1ab_0
  - huggingface_hub=0.2.1=pyhd8ed1ab_0
  - idna=3.1=pyhd3deb0d_0
  - importlib-metadata=4.6.4=py39h2804cbe_0
  - importlib_metadata=4.6.4=hd8ed1ab_0
  - iniconfig=1.1.1=pyh9f0ad1d_0
  - jbig=2.1=h3422bc3_2003
  - jinja2=3.0.3=pyhd8ed1ab_0
  - joblib=1.0.1=pyhd8ed1ab_0
  - jpeg=9d=h27ca646_0
  - lcms2=2.12=had6a04f_0
  - lerc=2.2.1=h9f76cd9_0
  - libblas=3.9.0=11_osxarm64_openblas
  - libcblas=3.9.0=11_osxarm64_openblas
  - libcxx=12.0.1=h168391b_0
  - libdeflate=1.7=h27ca646_5
  - libffi=3.3=h9f76cd9_2
  - libgfortran=5.0.0.dev0=11_0_1_hf114ba7_23
  - libgfortran5=11.0.1.dev0=hf114ba7_23
  - liblapack=3.9.0=11_osxarm64_openblas
  - libopenblas=0.3.17=openmp_h5dd58f0_1
  - libpng=1.6.37=hf7e6567_2
  - libprotobuf=3.16.0=hccf11d3_0
  - libtiff=4.3.0=hc6122e1_1
  - libwebp-base=1.2.1=h3422bc3_0
  - llvm-openmp=12.0.1=hf3c4609_1
  - lz4-c=1.9.3=hbdafb3b_1
  - markupsafe=2.0.1=py39h5161555_1
  - more-itertools=8.8.0=pyhd8ed1ab_0
  - ncurses=6.2=h9aa5885_4
  - ninja=1.10.2=h4d860bb_0
  - nltk=3.6.2=pyhd8ed1ab_0
  - numpy=1.21.4=py39h1f3b974_0
  - olefile=0.46=pyh9f0ad1d_1
  - openai=0.11.4=py39h2804cbe_0
  - openjpeg=2.4.0=h062765e_1
  - openpyxl=3.0.9=pyhd8ed1ab_0
  - openssl=1.1.1q=ha287fd2_0
  - packaging=21.0=pyhd8ed1ab_0
  - pandas=1.3.4=py39h7f752ed_1
  - pandas-stubs=1.2.0.38=py39h2804cbe_0
  - pillow=8.3.2=py39ha74c66e_0
  - pip=21.2.4=pyhd8ed1ab_0
  - pluggy=0.13.1=py39h2804cbe_4
  - py=1.10.0=pyhd3deb0d_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pydantic=1.8.2=py39h5161555_2
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pysocks=1.7.1=py39h2804cbe_3
  - pytest=6.2.5=py39h2804cbe_1
  - python=3.9.7=h54d631c_3_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-tzdata=2022.1=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytorch=1.9.0=cpu_py39he8fdc14_2
  - pytorch-cpu=1.9.0=cpu_py39hd610c6a_2
  - pytz=2021.3=pyhd8ed1ab_0
  - pytz-deprecation-shim=0.1.0.post0=py39h2804cbe_2
  - pyyaml=5.4.1=py39h5161555_1
  - readline=8.1=hedafd6a_0
  - regex=2021.8.21=py39h5161555_0
  - requests=2.26.0=pyhd8ed1ab_0
  - sacremoses=0.0.43=pyh9f0ad1d_0
  - scikit-learn=0.24.2=py39hef7049f_1
  - scipy=1.7.0=py39h5060c3b_0
  - sentence-transformers=2.1.0=pyhd8ed1ab_0
  - sentencepiece=0.1.95=py39h4d2d688_1
  - setuptools=57.4.0=py39h2804cbe_0
  - six=1.16.0=pyh6c4a22f_0
  - sleef=3.5.1=h27ca646_1
  - sqlite=3.36.0=h72a2b83_0
  - starlette=0.14.2=pyhd8ed1ab_0
  - threadpoolctl=2.2.0=pyh8a188c0_0
  - tk=8.6.11=he1e0b03_0
  - tokenizers=0.10.3=py39hab32027_1
  - toml=0.10.2=pyhd8ed1ab_0
  - torchvision=0.10.1=py39h0a40b5a_0_cpu
  - tqdm=4.62.1=pyhd8ed1ab_0
  - transformers=4.14.1=pyhd8ed1ab_0
  - typing-extensions=3.10.0.0=hd8ed1ab_0
  - typing_extensions=3.10.0.0=pyha770c72_0
  - tzdata=2021a=he74cb21_1
  - tzlocal=4.2=py39h2804cbe_1
  - urllib3=1.26.6=pyhd8ed1ab_0
  - uvicorn=0.16.0=py39h2804cbe_0
  - wheel=0.37.0=pyhd8ed1ab_1
  - xz=5.2.5=h642e427_1
  - yaml=0.2.5=h642e427_0
  - zipp=3.5.0=pyhd8ed1ab_0
  - zlib=1.2.11=h31e879b_1009
  - zstd=1.5.0=h861e0a7_0
prefix: /opt/homebrew/Caskroom/miniforge/base/envs/khoj
