name: khoj
channels:
  - conda-forge
dependencies:
  - python=3.8.*
  - numpy=1.22.4
  - pytorch=1.13.1
  - torchvision=0.14.1
  - transformers=4.21.0
  - sentence-transformers=2.1.0
  - fastapi=0.77.1
  - uvicorn=0.17.6
  - pyyaml=6.0
  - pytest=7.1.2
  - pillow=9.3.0
  - openai=0.20.0
  - pydantic=1.9.1
  - jinja2=3.1.2
  - aiofiles=0.8.0
  - huggingface_hub=0.8.1
  - dateparser=1.1.1
  - schedule=1.1.0