name: pypi

on:
  push:
    tags:
      - "*"
    branches:
      - 'master'
      - 'release/1.x'
    paths:
      - src/khoj/**
      - src/interface/web/**
      - pyproject.toml
      - .github/workflows/pypi.yml
  pull_request:
    branches:
      - 'master'
      - 'release/1.x'
    paths:
      - src/khoj/**
      - src/interface/web/**
      - pyproject.toml
      - .github/workflows/pypi.yml
  workflow_dispatch:

jobs:
  publish:
    name: Publish Python Package to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Set up Python 3.11
        run: uv python install 3.11

      - name: ‚¨áÔ∏è Install Server
        run: uv sync --all-extras

      - name: ‚¨áÔ∏è Install Web Client
        run: |
          yarn install
          yarn pypiciexport
        working-directory: src/interface/web

      - name: üìÇ Copy Generated Files
        run: |
          mkdir -p src/khoj/interface/compiled
          cp -r $(uv python find-python 3.11)/lib/python3.11/site-packages/khoj/interface/compiled/* src/khoj/interface/compiled/

      - name: ‚öôÔ∏è Build Python Package
        run: |
          # Setup Environment for Reproducible Builds
          export PYTHONHASHSEED=42
          export SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)
          rm -rf dist

          # Build PyPI Package
          uv build

      - name: üå°Ô∏è Validate Python Package
        run: |
          # Validate PyPi Package
          uv tool run check-wheel-contents dist/*.whl --ignore W004
          uv tool run twine check dist/*

      - name: ‚è´ Upload Python Package Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: khoj
          path: dist/khoj-*.whl

      - name: üì¶ Publish Python Package to PyPI
        if: startsWith(github.ref, 'refs/tags') || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/release/1.x'
        uses: pypa/gh-action-pypi-publish@release/v1.12
        with:
          skip-existing: true
          print-hash: true
